import type { Metadata } from "next";
import Head from 'next/head';
import { Inter } from "next/font/google";
import "../styles/RootLayout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, title, description }: Readonly<{children: React.ReactNode, title: string, description: string}>) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        {children}
      </div>
    </>
  );
}
